<?php
  $message = array(
    "Settings" => "Settings",
    "CMS Configurations:" => "CMS Configuration",
    "Global settings" => "Global settings",
    "Localization" => "Localization",
    "Accounts" => "Accounts",
    "Account type:" => "Account type:",
    "Admins" => "Admins",
    "Admin permissions" => "Admin permissions",
    "Admin module permissions" => "Admin module permissions",
    "Users" => "Users",
    "User permissions" => "User permissions",
    "User module permissions" => "User module permissions",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
    "" => "",
  )
?>
